### ISSUE TITLE
[INFO] Are PCBs/kits available ?

### ISSUE THREAD

**Issue by amontefusco** [UR3IQO/AngeliaLite#1]
Hi, 
nice project.

Are you going to publish PCB layouts or selling them?

**Comment by UR3IQO** [comment]
Hi,
Currently I have no spare PCBs or kits. The spare boards I had earlier I gave to Pavel US4ICI. So, he has  several fully assembled and checked boards. He will probably sell some of them - please contact him for details.

It is still open question if AngeliaLite will become open hardware project. At this moment I have no such plans, but who knows...

**Comment by amontefusco** [comment]
Ok, Thanks for the info.
